---
title: SMBS GROUPE
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  categories:
    title: categories
    output: true
  marques:
    title: marques
    output: true
  produits:
    title: produits
    output: true
  sliders:
    title: sliders
    output: true
defaults:
- scope:
    path: ''
    type: produits
  values:
    layout: product
    defaults: 
- scope:
    path: ''
    type: categories
  values:
    layout: category
email: ali.karaki@smbs.com
address: 19, Rue Robert Brun
showroom: Rue 6 Felix Éboué
telephone: "+221 33 822 15 11"
description: 'Spécialisée dans le commerce de la distribution et de l’exportation
  d’équipements de boulangerie, de pâtisserie, d’hôtellerie, de restauration (Traiteurs,
  Points Chauds) issue de l’importation directement en enfin fournisseur matériel
  BTP et des groupes électrogènes importés. '
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
logo: "/uploads/logo.png"
parallax1: "/uploads/slider12.jpg"
parallax2: "/uploads/slider12.jpg"
parallax3: "/uploads/slider12.jpg"
