---
title: SMBS GROUPE
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  categories:
    title: categories
    output: true
  marques:
    title: marques
    output: true
  produits:
    title: produits
    output: true
  sliders:
    title: sliders
    output: true
email: ali.karaki@smbs.com
address: 19, Rue Robert Brun
showroom: Rue 6 Felix Éboué
telephone: "+221 33 822 15 11"
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
logo: "/uploads/logo.png"
parallax1: "/uploads/slider12.jpg"
parallax2: "/uploads/slider12.jpg"
parallax3: "/uploads/slider12.jpg"
